name: Delete Old Files

on:
  schedule:
    # 每天运行一次。你可以根据需要调整时间间隔。
    - cron: '0 0 * * *'

jobs:
  delete_old_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g moment

    - name: Delete files older than 7 days
      run: |
        # Find and delete files older than 7 days
        find . -type f -mtime +7 -exec rm -f {} \;

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Delete files older than 7 days"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
